# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cce9333e778d99c2da4da3a6f430f6445123bf2e8896de2ae7020fa2b83b67bb5644569ddc7c2085ec0db3343551bd6757d3d96cc367f438e0b04f82e78ff6fd

test:
  secret_key_base: 53018346a13fd698550e5627f345b389610e1c6d6e8cb8d9cc1397e84c194cb2c67b3882864b32421588d65b9404fdf297a14b87eb01e221ae8ed4e537b19e5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
